---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Validate PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions: {}

concurrency:
  group: validate-pr-title-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  lint-pr:
    name: Validate PR title
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
